// Generated by CoffeeScript 1.12.5
(function() {
  var back, checkRoman, custom, fromRoman, next, pad, toRoman, toc, update;

  update = function(num) {
    return document.getElementById("customnum").value = num;
  };

  checkRoman = function(roman) {
    return /^[a-zA-Z]+$/.test(roman);
  };

  next = function() {
    var num, padded, url;
    url = document.getElementById("PDF").src;
    num = url.split("12_")[1];
    num = num.split(".")[0];
    if (num === 'xix') {
      num = '-1';
    }
    if (checkRoman(num)) {
      num = fromRoman(num.toUpperCase());
      num = parseInt(num);
      num = num + 1;
      num = (toRoman(num)).toLowerCase();
      padded = num;
    } else {
      num = parseInt(num);
      num = num + 1;
      padded = pad(num, 4);
    }
    update(num);
    return document.getElementById("PDF").src = "https://my.hrw.com/math12/na_cc/hsm_larson/student/pdf/english/alg2/alg2_cc_na_lar_12_" + padded + ".pdf";
  };

  back = function() {
    var num, padded, url;
    url = document.getElementById("PDF").src;
    num = url.split("12_")[1];
    num = num.split(".")[0];
    if (checkRoman(num)) {
      num = fromRoman(num.toUpperCase());
      num = parseInt(num);
      num = num - 1;
      num = (toRoman(num)).toLowerCase();
      padded = num;
    } else {
      num = parseInt(num);
      num = num - 1;
      padded = pad(num, 4);
    }
    update(num);
    return document.getElementById("PDF").src = "https://my.hrw.com/math12/na_cc/hsm_larson/student/pdf/english/alg2/alg2_cc_na_lar_12_" + padded + ".pdf";
  };

  custom = function() {
    var num, padded, url;
    url = document.getElementById("PDF").src;
    num = document.getElementById("customnum").value;
    if (!checkRoman(num)) {
      num = parseInt(num);
      padded = pad(num, 4);
    } else {
      padded = num;
    }
    alert(padded);
    return document.getElementById("PDF").src = "https://my.hrw.com/math12/na_cc/hsm_larson/student/pdf/english/alg2/alg2_cc_na_lar_12_" + padded + ".pdf";
  };

  toc = function() {
    document.getElementById("customnum").value = "viii";
    return custom();
  };

  pad = function(number) {
    if (number <= 9999) {
      number = ("000" + number).slice(-4);
    }
    return number;
  };

  toRoman = function(num) {
    var decimal, i, j, ref, result, roman;
    result = '';
    decimal = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1];
    roman = ["M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"];
    for (i = j = 0, ref = decimal.length; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      while (num % decimal[i] < num) {
        result += roman[i];
        num -= decimal[i];
      }
    }
    return result;
  };

  fromRoman = function(str) {
    var decimal, i, j, ref, result, roman;
    result = 0;
    decimal = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1];
    roman = ["M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"];
    for (i = j = 0, ref = decimal.length; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      while (str.indexOf(roman[i]) === 0) {
        result += decimal[i];
        str = str.replace(roman[i], '');
      }
    }
    return result;
  };

  window.onload = function() {
    document.getElementById('next').onclick = next;
    document.getElementById('back').onclick = back;
    document.getElementById('toc').onclick = toc;
    return document.getElementById('submit').onclick = custom;
  };

}).call(this);
