// Generated by CoffeeScript 1.12.5
(function() {
  var back, custom, next, pad;

  next = function() {
    var num, padded, url;
    url = document.getElementById("PDF").src;
    num = url.slice(86, 90);
    num = parseInt(num);
    num = num + 1;
    padded = pad(num, 4);
    return document.getElementById("PDF").src = "https://my.hrw.com/math12/na_cc/hsm_larson/student/pdf/english/alg2/alg2_cc_na_lar_12_" + padded + ".pdf";
  };

  back = function() {
    var num, padded, url;
    url = document.getElementById("PDF").src;
    num = url.slice(86, 90);
    num = parseInt(num);
    num = num - 1;
    padded = pad(num, 4);
    return document.getElementById("PDF").src = "https://my.hrw.com/math12/na_cc/hsm_larson/student/pdf/english/alg2/alg2_cc_na_lar_12_" + padded + ".pdf";
  };

  custom = function() {
    var num, padded, url;
    url = document.getElementById("PDF").src;
    num = document.getElementById("customnum").value;
    num = parseInt(num);
    padded = pad(num, 4);
    return document.getElementById("PDF").src = "https://my.hrw.com/math12/na_cc/hsm_larson/student/pdf/english/alg2/alg2_cc_na_lar_12_" + padded + ".pdf";
  };

  pad = function(number) {
    if (number <= 9999) {
      number = ("000" + number).slice(-4);
    }
    return number;
  };

  window.onload = function() {
    document.getElementById('next').onclick = next;
    document.getElementById('back').onclick = back;
    return document.getElementById('submit').onclick = custom;
  };

}).call(this);
